services:
  go:
    build:
      context: ./backend
    ports:
      - "8080:8080"
  nextjs:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
