version: "3.7"
services:
  go:
    build:
      context: .
      target: backend
      dockerfile: Dockerfile
  nextjs:
    build:
      context: .
      target: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
