version: "3.7"
services:
  go:
    build:
      context: .
      target: backend
      dockerfile: Dockerfile
  nextjs:
    build:
      context: .
      target: frontend_dev
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
